# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14-j3yFacRNIWfH80uN6vUjNFpNZR70Rb
"""

import streamlit as st
import random

st.set_page_config(layout='wide')
st.title('Test Streamlit')

st.write('Hi!')

if st.button('Generate Random Number'):
    random_number = random.randint(1,100)
    st.write(f'Random Number: {random_number}')